from setuptools import setup, find_packages

setup(
    name="audio-processing-tool",
    version="1.0.0",
    packages=find_packages(),
    install_requires=[
        "librosa>=0.10.1",
        "numpy>=1.26.4",
        "soundfile>=0.12.1",
        "streamlit>=1.31.1",
        "pydub>=0.25.1",
        "torch>=2.2.0",
        "torchaudio>=2.2.0",
        "transformers>=4.37.2",
        "scipy>=1.12.0",
        "matplotlib>=3.8.2",
        "plotly>=5.18.0",
        "pandas>=2.2.0",
        "scikit-learn>=1.4.0",
        "python-dotenv>=1.0.0",
        "tensorflow>=2.15.0",
        "tensorflow-hub>=0.15.0",
        "tensorflow-io>=0.35.0",
        "noisereduce>=3.0.0",
        "pedalboard>=0.8.7",
        "audioread>=3.0.1"
    ],
    author="Abhishek Banerjee",
    author_email="abhishekninja@yahoo.com",
    description="A sophisticated Python application for audio analysis and processing",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/newloverofcode2025/audio-processing-tool",
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    python_requires=">=3.8",
)
